# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6addcecbdc42d0e15ca315868c510264"
name = "SimpleVolumeDiscountApp"
handle = "simplevolumediscountapp-1"
application_url = "https://sources-blocked-bare-mounted.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "test-app-devit.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_discounts,write_discounts,read_checkouts"

[auth]
redirect_urls = [
  "https://sources-blocked-bare-mounted.trycloudflare.com/auth/callback",
  "https://sources-blocked-bare-mounted.trycloudflare.com/auth/shopify/callback",
  "https://sources-blocked-bare-mounted.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
